
EX1: ./Exercise1/main.c
	gcc -o EX1 ./Exercise1/main.c
EX2: ./Exercise2/main.c
	gcc -o EX2 ./Exercise2/main.c
Zombie: ./Exercise3/Zombie/main.c
	gcc -o Zombie ./Exercise3/Zombie/main.c
Orphan: ./Exercise3/Orphan/main.c
	gcc -o Orphan ./Exercise3/Orphan/main.c
all: EX1 EX2 Zombie Orphan

clean:
	rm -rf EX1
	rm -rf EX2
	rm -rf Zombie
	rm -rf Orphan