Exercise1: ./Exercise1/main.c
	gcc -o EX1 ./Exercise1/main.c
Exercise2: ./Exercise2/main.c
	gcc -o EX2 ./Exercise2/main.c
Exercise3: ./Exercise3/main.c
	gcc -o EX3 ./Exercise3/main.c
Exercise4: ./Exercise4/main.c
	gcc -o EX4 ./Exercise4/main.c
all: Exercise1 Exercise2 Exercise3

clean:
	rm -rf EX1
	rm -rf EX2
	rm -rf EX3
	rm -rf EX4