EX1: ./Exercise1/main.c
	gcc -o EX1 ./Exercise1/main.c
EX2: ./Exercise2/main.c
	gcc -o EX2 ./Exercise2/main.c
EX3: ./Exercise3/main.c
	gcc -o EX3 ./Exercise3/main.c
EX4: ./Exercise4/main.c
	gcc -o EX4 ./Exercise4/main.c
all: EX1 EX2 EX3 EX4

clean:
	rm -rf EX1 EX2 EX3 EX4
